#!/usr/bin/env bash

source /etc/makepkg.conf

PACKAGER="${PACKAGER:-k3apps CI}"
GPGKEY="${ARCH_REPO_GPG_KEY_ID:-${GPGKEY:-}}"

MAKEFLAGS="${MAKEFLAGS:--j$(nproc)}"
BUILDDIR="${BUILDDIR:-/tmp/makepkg}"
PKGDEST="${PKGDEST:-}"
SRCDEST="${SRCDEST:-}"
SRCPKGDEST="${SRCPKGDEST:-}"
LOGDEST="${LOGDEST:-}"

